### ISSUE TITLE
Gravity isn't calculated correctly when non-default dimensions are used

### ISSUE THREAD

**Issue by ataulm** [keyboardsurfer/Crouton#112]
I set the height of a `Crouton` using the `Style.Builder`:

    Style INFO = new Style.Builder()
                        .setBackgroundColorValue(holoBlueLight)
                        .setHeightDimensionResId(R.dimen.actionbar_height)
                        .build();

The text isn't vertically centered, so I try

    .setGravity(Gravity.CENTER)

and

    .setGravity(Gravity.VERTICAL_CENTER)

neither of which work. When it's set to `VERTICAL_CENTER` the text aligns to the left, so at least `HORIZONTAL_CENTER` works.

I also tried when setting the width of the Crouton:

    Style INFO = new Style.Builder()
                        .setBackgroundColorValue(holoBlueLight)
                        .setWidth(500)
                        .build();

Here, the text is in the horizontal center of the screen, not the Crouton view.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
