### ISSUE TITLE
Problem when using with ListActivity

### ISSUE THREAD

**Issue by Chezlui** [keyboardsurfer/Crouton#117]
After a lot of headaches, I found that the inocent thing that was breaking my code it was my loved croutons...

When deleting an item in a ListView within a ListActivity, I show a crouton to notificate but after that my adapter must be setted to null so it appears empty list instead of the rest of the filled list.

This is the code:

    public class ExamenesAnteriores_activity extends ListActivity {

      private ExamenesDataSource examenDS;
      private Cursor cursor;
      public ExamenCursorAdapter examenAdapter = null;
      private ListView listaV;

      public static final int C_VISUALIZAR = 551;
      public static final int C_ELIMINAR = 552;

      @Override
        protected void onCreate(Bundle savedInstanceState) {
          super.onCreate(savedInstanceState);
          setContentView(R.layout.activity_examenes_anteriores);

          listaV = (ListView) findViewById(android.R.id.list);

          examenDS = new ExamenesDataSource(this);
          examenDS.open();

          consultar();

          registerForContextMenu(this.getListView());

        }

      private void consultar() {
        cursor = examenDS.getCursorAllExam();
        startManagingCursor(cursor);
        examenAdapter = new ExamenCursorAdapter(this, cursor);
        listaV.setAdapter(examenAdapter);
      }

      private void borrar(final long id) {
        //
        // Borramos el registro y refrescamos la lista
        //
        AlertDialog.Builder dialogEliminar = new AlertDialog.Builder(this);

        dialogEliminar.setIcon(android.R.drawable.ic_dialog_alert);
        dialogEliminar.setTitle("Borrar examen");
        dialogEliminar.setMessage("¿Estás seguro?");
        dialogEliminar.setCancelable(false);

        dialogEliminar.setPositiveButton(getResources().getString(android.R.string.ok), new DialogInterface.OnClickListener() {

            public void onClick(DialogInterface dialog, int boton) {
            borrarExamen((int)id);
            consultar();
            }
            });

        dialogEliminar.setNegativeButton(android.R.string.no, null);

        dialogEliminar.show();

      }

      public void borrarExamen(int id) {
        examenDS.deleteExamen(id);
        Crouton.makeText(this, "Examen borrado con internal Id: " + id, Style.INFO).show();

      }

      @Override
        public void onCreateContextMenu(ContextMenu menu, View v,
            ContextMenuInfo menuInfo) {
          super.onCreateContextMenu(menu, v, menuInfo);

          menu.setHeaderTitle(cursor.getString(
                cursor.getColumnIndex(Examenes_DBH.COLUMN_EXAMEN_ID)));
          menu.add(Menu.NONE, C_ELIMINAR, Menu.NONE, "Eliminar");
        }

      @Override
        public boolean onCreateOptionsMenu(Menu menu) {
          // Inflate the menu; this adds items to the action bar if it is present.
          getMenuInflater().inflate(
              R.menu.examenes_anteriores_activity, menu);
          return true;
        }

      @Override
        public boolean onContextItemSelected(MenuItem item) {
          AdapterContextMenuInfo info = (AdapterContextMenuInfo) item.getMenuInfo();
          Intent in;
          switch(item.getItemId())
          {
            case C_ELIMINAR:
              borrar(info.id);
              return true;

          }

          return super.onContextItemSelected(item);
        }

    }

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
