### ISSUE TITLE
Issue on Configuration DURATION_INFINITE

### ISSUE THREAD

**Issue by sumitsahoo** [keyboardsurfer/Crouton#140]
If a crouton is already active, trying to activate it again will cause a freeze. Click listener on crouton will not work. Only way to remove it is to destroy the activity. Rotating device also gets rid of the crouton as it destroys the activity.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
