### ISSUE TITLE
Crouton translucent status bar position.

### ISSUE THREAD

**Issue by mecid** [keyboardsurfer/Crouton#152]
Hello i am using translucent statusbar in my app without using fitsSystemBar.
I am using system tint bar lib for adding top padding to android.R.id.content, but Crouton place under actionbar + this padding. This is screenshot

![screenshot_2014-02-06-02-58-01](https://f.cloud.github.com/assets/324372/2093454/342cd632-8eb9-11e3-921e-88323c49adfb.png)

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
