### ISSUE TITLE
The width of a custom view used in a Crouton is being incorrectly calculated

### ISSUE THREAD

**Issue by fernandocamargoti** [keyboardsurfer/Crouton#166]
I've created a custom view to display using the Crouton library. This view has some margin, a background and a TextView with MATCH_PARENT width. This TextView is multiline and has a left drawable.

The problem I'm facing is that when I show it with the Crouton, the TextView's width is calculated incorrectly, making the text to cut off. It's very strange because it only happens the first time my Fragment is created. If I rotate the screen to landscape and rotate again to portrait, it shows normally. I'm showing the crouton inside the onStart() method of my fragment, that I add to the Activity on runtime.

The following link in StackOverflow has more details about the issue, including screenshots:

http://stackoverflow.com/questions/22334921/the-width-of-a-custom-view-used-in-a-crouton-is-being-incorrectly-calculated

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
