### ISSUE TITLE
Action bar overlay?

### ISSUE THREAD

**Issue by aryaxt** [keyboardsurfer/Crouton#168]
How do you handle repositioning of a crouton when action bar overlay is on?

I have a weird case where the crouton goes below my action bar. My hacky solution for now is to add a custom view and add top padding when the action bar is visible?

Is that something that this library doesn't handle automatically? or am I doing something wrong?

Thanks

**Comment by ppamorim** [comment]
Not working here.
+1

**Comment by keyboardsurfer** [comment]
Can you post a screenshot of the result when attaching a Crouton to the Toolbar as described in my comment above?

**Comment by ppamorim** [comment]
Not attached:

![problem](https://cloud.githubusercontent.com/assets/5521682/5781723/2230b1ae-9d9c-11e4-952e-d7d80831facd.jpg)

Attached: ... Not showing

**Comment by keyboardsurfer** [comment]
You probably need to fiddle around with the `LayoutParams` in order to get this working or might try to attach it to your `ViewGroup` container.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
