### ISSUE TITLE
Show crouton for a specified time

### ISSUE THREAD

**Issue by gabrielittner** [keyboardsurfer/Crouton#18]
I'd really like to have an option display the crouton for a before specified time, like a toast.

**Comment by pishguy** [comment]
@keyboardsurfer 

i'm using your introduced link and i', trying to set specific time for that, but i can't set that to other specific time, for example:

```
    Crouton crouton = Crouton.makeText(activity, AndroidUtilities.getString(R.string.publish_type_without_choise_cost_is_not_possible, context),
            new Style.Builder()
                    .setTextSize((int) AndroidUtilities.getAdjustTextSize(activity, context))
                    .setBackgroundColor(android.R.color.holo_red_dark)
                    .setTextColor(android.R.color.white)
                    .setHeight(100)
                    .setDuration(1)
                    .setPaddingInPixels(10)
                    .setFontName("fonts/shabnam_bold.ttf")
                    .build(), channelContentRootLayout);
    crouton.show();
```

in this code `.setDuration(1)` doesnt work

**Comment by keyboardsurfer** [comment]
The code does what it is intended to to. It displays a Crouton for the specified time of 1 millisecond.

If you want to be able to properly read the message I recommend increasing the duration to at least one second (1000 milliseconds) or use one of the default values.
