### ISSUE TITLE
Using Crouton with ViewGroup

### ISSUE THREAD

**Issue by HappyDr0id** [keyboardsurfer/Crouton#188]
I developp an app with minSdk:14 and targetSdk:19. 

If I use the simple method 'makeText(Activity activity, CharSequence text, Style style)', everything is okay, the Crouton is displayed on the top of my Activity and with a solid background. 

But if I want to put it on the top of a RelativeLayout using this method : 'makeText(Activity activity, CharSequence text, Style style, ViewGroup viewGroup)' then the Crouton is displayed with a transparent background. I use the default Style.INFO and even if I make my own Style with an opaque background color, or a custom view with an opaque color, the result is always a transparent Crouton.

This is quite weird because it is a common use of the library and I didn't find any person referencing this issue, except on this stackoverflow : http://stackoverflow.com/questions/19231596/remove-croutons-messages-transparency.

I am maybe missing something, thanks in advance for your answer :)

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
