### ISSUE TITLE
Crouton "destroys" PreferenceFragment

### ISSUE THREAD

**Issue by gabrielittner** [keyboardsurfer/Crouton#19]
This is how my PreferenceFragment looks like: https://picasaweb.google.com/lh/photo/QbpRCxQHqVATtMqhpP7OPhehlnpMhIUyAwoYnhPIGog?feat=directlink
When showing a Crouton:
https://picasaweb.google.com/lh/photo/MJwaGoIBiO7NNtpmprypnBehlnpMhIUyAwoYnhPIGog?feat=directlink

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
