### ISSUE TITLE
Adding Crouton as part of a layout causes it to refresh

### ISSUE THREAD

**Issue by 1zaman** [keyboardsurfer/Crouton#196]
Since `Crouton` display is always posted on the message queue instead of being processed immediately, adding a `Crouton` to a new `View` hierarchy causes it to be layout twice, creating a flickering effect. Immediately adding the `Crouton` to the layout should solve this issue.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
