### ISSUE TITLE
Crouton bleeding 

### ISSUE THREAD

**Issue by ravishanker** [keyboardsurfer/Crouton#199]
How to reproduce the problem:
While a crouton is displayed on a view lock or screen-off the phone.  Then screen-on and unlock to see the problem.  The Layout is expanding to full screen.  See image
![screenshot_2014-07-30-15-02-11](https://cloud.githubusercontent.com/assets/990349/3745886/02681c6c-17b5-11e4-9b01-25f02230b899.png)

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
