### ISSUE TITLE
Crouton not showing outAnimation

### ISSUE THREAD

**Issue by choiruru** [keyboardsurfer/Crouton#210]
If we use custom view like 
**crouton = Crouton.makeText(getActivity(), "foo", Style.GREEN, R.id.alternate_view_group)**,
 and setting view 
**android:layout_height="wrap_content"** , 
outAnimation cant showing. I found solution in [this](http://stackoverflow.com/questions/22196989/crouton-not-showing-outanimation), but it didnt help because it use  view 
**android:layout_height="match_parent"** 
that can take large space of my layout. Anyone else has experienced this too or has an idea why it's not working?

**Comment by pakoito** [comment]
Can confirm this. It's annoying because when tying it up with behaviour, 400ms of animation not playing need to be taken into account.

**Comment by juliocotta** [comment]
The animation seems to run ok if there is no viewGroup set, but is not being played if otherwise.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
