### ISSUE TITLE
Check if there are crouton to show or visible

### ISSUE THREAD

**Issue by skimarxall** [keyboardsurfer/Crouton#212]
Sometimes the user gets nervous when it sees a view over the other (in this case a crouton) I think it's need a method to check if there are visible or in queue crouton and handle that onBackPressed so the crouton is removed.

I think it would be a good feature.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
