### ISSUE TITLE
Does not compile with Gradle

### ISSUE THREAD

**Issue by powder366** [keyboardsurfer/Crouton#214]
$ gradle assemble
Creating properties on demand (a.k.a. dynamic properties) has been deprecated and is scheduled to be removed in Gradle 2.0. Please read http://gradle.org/docs/current/dsl/org.gradle.api.plugins.ExtraPropertiesExtension.html for information on the replacement for dynamic properties.
Deprecated dynamic property: "artifactId" on "project ':crouton-library'", value: "crouton".

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/code/studio/libraries/Crouton/library/build.gradle' line: 96

* What went wrong:
A problem occurred evaluating project ':crouton-library'.
> No such property: repositoryUrl for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer
  Possible solutions: repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.749 secs

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
