### ISSUE TITLE
Update default styles (ALERT, INFO, CONFIRM) as per material color palette 

### ISSUE THREAD

**Issue by MufriA** [keyboardsurfer/Crouton#218]
Will there be any updates to default styles as per new [color material color palatte](http://www.google.com/design/spec/style/color.html#color-ui-color-palette).

Of course we can use use custom styles, it would be nice if we can change basic styles based on new palette.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
