### ISSUE TITLE
Not showing below Toolbar

### ISSUE THREAD

**Issue by ppamorim** [keyboardsurfer/Crouton#227]
I noticed a problem to show the Crouton below the Toolbar, I've added the last params (Toolbar) to viewGroup and still not showing. Without this params, works perfectly, but above the Toolbar.

![problem](https://cloud.githubusercontent.com/assets/5521682/5776614/54b331c2-9d71-11e4-962a-8327680c0131.jpg)

**Comment by troytang** [comment]
I have the same problem, too.

**Comment by MichaelGirgis** [comment]
I also have the same problem

**Comment by ShkurtiA** [comment]
Same here

**Comment by sharan01** [comment]
same here

**Comment by hardikamal** [comment]
+1

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
