### ISSUE TITLE
Need remove delayed messages API.

### ISSUE THREAD

**Issue by segoviamin** [keyboardsurfer/Crouton#228]
I'm implementing close current crouton feature. 
But the problem is handler Message still remained. 
So if I use close and open again, oped crouton closed when previous Messages.REMOVE_CROUTON called. 

Would you make one API can call `removeAllMessages();` or `removeAllMessagesForCrouton(crouton);`

**Comment by keyboardsurfer** [comment]
The `REMOVE_CROUTON` message is meant to remove messages from the queue. So this is working as intended.

**Comment by segoviamin** [comment]
Hi Benjamin.
Thank you for your fast reply. 

I know `removeCrouton(crouton)` is called from `Messages.REMOVE_CROUTON`, 
But when I intentionally call `crouton.hide()`, `Messages.REMOVE_CROUTON` message is still remained. And it is launched later.

So I wish to call `removeAllMessagesForCrouton(crouton);` inside of `protected void removeCrouton(Crouton crouton) ` method.

Or `void hide()` can have such a `Manager.getInstance().removeCroutonAndMessage(this);` for example. 

Thank you for spending your time to read this request.

**Comment by keyboardsurfer** [comment]
Calling `Crouton.hide()` will hide the Crouton with a delay to allow the out animation to take place.

If you want to remove the Crouton immediately, you can call [`Crouton.cancel()`](https://github.com/keyboardsurfer/Crouton/blob/master/library/src/main/java/de/keyboardsurfer/android/widget/crouton/Crouton.java#L563)
