### ISSUE TITLE
cancellAllCroutons doesnt fire onRemoved callback

### ISSUE THREAD

**Issue by omgreel** [keyboardsurfer/Crouton#230]
I see it's not complicated to make cancelAllCroutons func to fire onRemoved callback.
I want to fork lib and make them to fire. Is there any problems I may get? Maybe callback are not firing because of reasons?

**Comment by keyboardsurfer** [comment]
I'm not going to merge this, as a callback like this should be implemented by each developer on an "as required" basis. I'm not aware of any issues that you might run into by default from my current point of view.
