### ISSUE TITLE
Animating several Croutons on the same ViewGroup displays previous instances

### ISSUE THREAD

**Issue by pakoito** [keyboardsurfer/Crouton#233]
My view contains a view group specifically for Croutons

```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/crouton"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content" />

<TextView
    android:layout_width="wrap_content"
    android:layout_height="0dp"
    android:layout_weight="1" />

<LinearLayout
    android:id="@+id/crouton"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content" />

</LLY>
```

Whenever I show a new crouton on @id/crouton

    Crouton.makeText(this, "error", Style.ERROR, croutonHolder).show();

the previous one is still showing, and is animated going out at the same time the new one comes in. I believe this is related to exit animations not being played.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.

**Comment by pakoito** [comment]
Noooooooooooooooooooooooooooooooooooo WTF

**Comment by pakoito** [comment]
Before you close shop and disappear, does the new library support for delayed croutons that appear only after the user comes back to UI?

**Comment by keyboardsurfer** [comment]
You can use [Snackbar](https://developer.android.com/reference/android/support/design/widget/Snackbar.html) to first create a Snackbar and then later on display it by calling `show()` on your Snackbar object.

**Comment by pakoito** [comment]
That's a huge downgrade along with styling, but we'll have to make do.

**Comment by keyboardsurfer** [comment]
Crouton still works the way it did before. You can still use it. But please fix bugs yourself. I'm available for merging fixes back in, but won't put any more effort in it.
