### ISSUE TITLE
Not able to use a white background

### ISSUE THREAD

**Issue by paolop** [keyboardsurfer/Crouton#235]
I'm just tying to use orange text over a white background obtaining a light blue background instead. This is the style I've defined:

final Style customStyle = new Style.Builder()
   .setBackgroundColorValue(getResources().getColor(R.color.white))
   .setTextColorValue(getResources().getColor(R.color.orange))
   .setTextSize(18).build();

where white is defined as #ffffff whereas orange is #ffed6900. I've also tried to achieve the same result for the background using a Drawable resource but the result is the same.

I've tested the above code on a nexus 5 (Android 5.1), nexus 7 (2013 - Android 4.4.2).

![screenshot_2015-04-16-15-48-51](https://cloud.githubusercontent.com/assets/349246/7182209/2e4bcab4-e450-11e4-9675-0f95600cdfb5.png)

**Comment by keyboardsurfer** [comment]
That looks like the default fallback color for backgrounds, `android.R.color.holo_blue_light`.
You can set a breakpoint [here](https://github.com/keyboardsurfer/Crouton/blob/master/library/src/main/java/de/keyboardsurfer/android/widget/crouton/Crouton.java#L835) and check whether the values match your expectation.

**Comment by paolop** [comment]
if(this.style.backgroundColorValue != Style.NOT_SET) is evaluating to true using .setBackgroundColorValue(getResources().getColor(R.color.white)). However using setBackgroundColor(R.color.white) is working.

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.

**Comment by paolop** [comment]
@keyboardsurfer already migrated. Thanks.
