### ISSUE TITLE
Memory leak in DefaultAnimationsBuilder

### ISSUE THREAD

**Issue by brunoaguiar** [keyboardsurfer/Crouton#239]
I'm using Crouton with LeakCanary and all the activities where I end up using an Crouton message I get a memory leak...

As recommended, I am calling Crouton.cancelAllCroutons(); in the onDestroy().

Here follows some info about the leak:
com.package.app.MainActivity has leaked:
* GC ROOT static de.keyboardsurfer.android.widget.crouton.DefaultAnimationsBuilder.slideInDownAnimation
* references android.view.animation.TranslateAnimation.mListenerHandler
* references android.view.ViewRootImpl$ViewRootHandler.this$0
* references android.view.ViewRootImpl.mContext
* leaks com.package.app.MainActivity instance
[ 05-26 14:13:51.729 14911:15308 D/LeakCanary ]

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.

**Comment by thuytrinh** [comment]
@brunoaguiar Would cancelAllCroutons() at onDestroy() fix the leak? I'm having the same issue but migrating to SnackBar is just overkill in the limitation of time we got now.

**Comment by brunoaguiar** [comment]
@thuytrinh I ended up giving up on Crouton, as it was deprecated...
But from what I remember that did not fix the issue.
