### ISSUE TITLE
Orientation changes prevent the Crouton queue to be displayed correctly.

### ISSUE THREAD

**Issue by keyboardsurfer** [keyboardsurfer/Crouton#24]
If there are a few Croutons within the queue and the device's orientation changes, all Croutons that have not yet been displayed will not be displayed.

Also Croutons that get added to the queue will not be displayed until the pre-orientation change queue has been fully processed.

This issue exists since the initial version of Crouton.

**Comment by emezias** [comment]
Note there is a Concurrency issue when following this direction. If placed in onDestroy, Crouton.cancelAllCroutons() can cancel any croutons that are supposed to be showing in the next activity. Better advice is to clear for the activity, as above and save CancelAll for an application ending action

**Comment by keyboardsurfer** [comment]
See [README](https://github.com/keyboardsurfer/Crouton#deprecation-notice) for further info.
