### ISSUE TITLE
not an issue :) but a question about Snackbar.

### ISSUE THREAD

**Issue by AndreiD** [keyboardsurfer/Crouton#242]
I guess you are the right person to ask... tried it in stackoverflow but no success

is there a way to make Snackbar look like Crouton.
Because just setting the gravity to top, it put's it in top, but the animation goes down... like it it's on button. 

so is there a way to make Snackbar behave like Crouton ? :) :clap: :star:

**Comment by keyboardsurfer** [comment]
The Snackbar pattern behaves differently than Croutons on intention.

The Snackbar [documentation](https://developer.android.com/reference/android/support/design/widget/Snackbar.html) says:

> They show a brief message at the bottom of the screen on mobile and lower left on larger devices. Snackbars appear above all other elements on screen and only one can be displayed at a time.

I'd stick with either pattern and use it the way they are intended.
But the [source for Snackbar](https://android.googlesource.com/platform/frameworks/support/+/master/design/src/android/support/design/widget/Snackbar.java) is also available. So you might be able to see what you can find there.

**Comment by AndreiD** [comment]
https://github.com/AndreiD/TSnackBar :)
