### ISSUE TITLE
Crouton with custom view and match_parent height

### ISSUE THREAD

**Issue by RlagoMan** [keyboardsurfer/Crouton#244]
Hi!
I cannot figure out how to make a crouton with a custom view, filling the entire screen (match_parent height). If I assign match_parent to a custom view, I get the same result as wrap_content.
I can see the Style.Builder#setHeight() method, but no way to use it with a custom view...
Am I missing something?
Thanks!

**Comment by keyboardsurfer** [comment]
Wrong forum. Use [StackOverflow](https://stackoverflow.com/questions/tagged/crouton).

**Comment by RlagoMan** [comment]
Maybe I have not expressed properly (or you have not understood what I meant).
Doesn't matter, thanks and good luck.
