### ISSUE TITLE
How to use in Fragment?

### ISSUE THREAD

**Issue by brunochichava** [keyboardsurfer/Crouton#246]
Hi im trying to use in a Fragment.

First i get a activity from Fragment like this `FragmentActivity act = this.getActivity();`

and then i create a Crouton like this: `Crouton.makeText(act, "Recaregado com sucesso", Style.ALERT).show();`

but the app creshes at that point.

**Comment by keyboardsurfer** [comment]
Please provide a stacktrace. Also at what stage of the lifecycle are you trying to access Crouton?
