### ISSUE TITLE
change position

### ISSUE THREAD

**Issue by pishguy** [keyboardsurfer/Crouton#247]
Hi, after make text by this code:

```
Crouton.makeText(activity, "ddddd", Style.ALERT).show();
```

its show top of my toolbar and i cant change position of that, please help me, Thanks

**Comment by amervelic** [comment]
Crouton.makeText(activity, "ddddd", Style.ALERT, ViewGroup).show();

**Comment by keyboardsurfer** [comment]
Basically what @amervelic said.

**Comment by pishguy** [comment]
@amervelic [I posted new issue as your help](https://github.com/keyboardsurfer/Crouton/issues/249)
